### ISSUE TITLE
UserWarning: implicit cast from 'char *' to a different pointer type

### ISSUE THREAD

**Issue by steamraven** [ereOn/csodium#1]
cffi 1.8.3 cares about the distinction between char and unsigned char and raises a warning now.  This seems to be caused by the `ffi.from_buffer()`.  Replacing with the following seems to suprress the warning:
`ffi.cast("unsigned char *", ffi.from_buffer())`

**Comment by ereOn** [comment]
@steamraven I could reproduce the problem and tried to fix it in [`e5ee709`](https://github.com/ereOn/csodium/commit/e5ee7094b2f0a664c2f6911b4139e5084470844e). Could you please confirm that it solves on your side too ?

Thanks.

**Comment by steamraven** [comment]
This solved one of them, but there are still more warnings. steamraven@c48e5a74cba44528843bf672a4a225ed5f5e9596

**Comment by ereOn** [comment]
@steamraven I just realized I did not push all my changes (I ammended locally but forgot to `force` push...)

Anyway, I merged your PR so I'll just discard those changes. Thanks !
